"""Generated quests and the weekly streak's freezes.

Mounted BEFORE routes/quests.py: `/quests/current` would otherwise be parsed
as `/quests/{quest_id}` and fail as a malformed UUID.

Reads here can write. Quests are generated by the first read of a period and
freezes are settled by the first read after a week closes (there is no cron),
so these take the level_progress lock like any other writer and commit.
"""

import datetime as dt
import uuid

from fastapi import APIRouter, HTTPException, status
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.api.deps import CurrentUser, DbSession
from app.core import quest_board as board
from app.core import streak_freezes as freezes
from app.core import workout_rules as rules
from app.core.progression import ProgressionDelta, apply_xp, lock_progress
from app.models.quest_board import AssignmentStatus, QuestAssignment, QuestPeriod
from app.models.user import User
from app.schemas.quest import ProgressionDeltaOut
from app.schemas.quest_board import (
    AssignmentOut,
    QuestBoardOut,
    RerollResponse,
    StreakStatusOut,
)

router = APIRouter(tags=["quest board"])


def _now() -> dt.datetime:
    return dt.datetime.now(dt.timezone.utc)


def assignment_out(a: QuestAssignment, *, rerolls_left: int) -> AssignmentOut:
    return AssignmentOut(
        id=a.id,
        template_code=a.template_code,
        title=a.title,
        description=a.description,
        period=a.period,
        objective_type=a.objective_type,
        progress=a.progress_value,
        target=a.target_value,
        reward_points=a.reward_points,
        status=a.status,
        completed_at=a.completed_at,
        ends_at=a.period_end,
        can_reroll=(
            a.period == QuestPeriod.DAILY.value
            and a.status == AssignmentStatus.ACTIVE.value
            and rerolls_left > 0
        ),
    )


def _delta_out(delta: ProgressionDelta) -> ProgressionDeltaOut:
    return ProgressionDeltaOut(
        **{**delta.__dict__, "leveled_up": delta.leveled_up, "ranked_up": delta.ranked_up}
    )


def _apply(progress, result: board.Refresh, user: User, now: dt.datetime) -> ProgressionDelta:
    """Credit what a refresh outside a workout earned: XP always, shop points
    when there was no live workout to carry them to its finish."""
    progress.points_balance += result.points_now
    return apply_xp(progress, xp=result.xp, at=now, tz_name=user.timezone)


def _board(db: Session, user: User, now: dt.datetime) -> QuestBoardOut:
    left = board.rerolls_left(db, user, now)
    rows = board.ensure_assignments(db, user, now)
    return QuestBoardOut(
        daily=[assignment_out(a, rerolls_left=left) for a in rows if a.period == QuestPeriod.DAILY.value],
        weekly=[assignment_out(a, rerolls_left=left) for a in rows if a.period == QuestPeriod.WEEKLY.value],
        rerolls_left=left,
    )


@router.get("/quests/current", response_model=QuestBoardOut)
def current_quests(current_user: CurrentUser, db: DbSession) -> QuestBoardOut:
    """Today's daily quests and this week's weekly quests, with progress.
    Generated on the first read of a period, the same ones on every read."""
    progress = lock_progress(db, current_user.id)
    now = _now()
    _apply(progress, board.refresh(db, current_user, now), current_user, now)
    out = _board(db, current_user, now)
    db.commit()
    return out


@router.post("/quests/assignments/{assignment_id}/reroll", response_model=RerollResponse)
def reroll_quest(
    assignment_id: uuid.UUID, current_user: CurrentUser, db: DbSession
) -> RerollResponse:
    """Swap one of today's active daily quests for another. 409 when none are
    left today, the quest is already done, or it is not a daily quest."""
    progress = lock_progress(db, current_user.id)
    assignment = db.execute(
        select(QuestAssignment).where(
            QuestAssignment.id == assignment_id, QuestAssignment.user_id == current_user.id
        )
    ).scalar_one_or_none()
    if assignment is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Quest not found")

    now = _now()
    try:
        fresh = board.reroll(db, current_user, assignment, now)
    except board.RerollError as exc:
        db.rollback()
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=str(exc)) from None
    except IntegrityError:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT, detail="No rerolls left today"
        ) from None

    result = board.refresh(db, current_user, now)
    delta = _apply(progress, result, current_user, now) if result.xp else None
    left = board.rerolls_left(db, current_user, now)
    db.refresh(fresh)
    response = RerollResponse(
        replaced=assignment.id,
        quest=assignment_out(fresh, rerolls_left=left),
        rerolls_left=left,
        progression=_delta_out(delta) if delta else None,
    )
    db.commit()
    return response


@router.get("/streak", response_model=StreakStatusOut)
def read_streak(current_user: CurrentUser, db: DbSession) -> StreakStatusOut:
    """The weekly workout streak with its freezes. Weeks that closed since the
    last read are settled first: a short week is covered automatically if a
    freeze is held, and freezes earned are added."""
    lock_progress(db, current_user.id)
    now = _now()
    streak, held = freezes.current_streak(db, current_user, now)
    out = StreakStatusOut(
        weeks=streak.weeks,
        this_week_sessions=streak.this_week_sessions,
        target=streak.target,
        this_week_done=streak.this_week_done,
        sessions_to_go=streak.sessions_to_go,
        freezes_held=held.balance,
        freeze_cap=rules.FREEZE_CAP,
        weeks_to_next_freeze=freezes.weeks_to_next(streak.weeks),
        freezes_used_unseen=freezes.covered_since(db, current_user, current_user.streak_seen_at),
    )
    db.commit()
    return out


@router.post("/streak/seen", status_code=status.HTTP_204_NO_CONTENT)
def acknowledge_streak(current_user: CurrentUser, db: DbSession) -> None:
    """The user has seen the "your streak was saved" notice; stop sending
    those weeks in `freezes_used_unseen`."""
    current_user.streak_seen_at = _now()
    db.commit()
