"""Shared column mixins."""

import datetime as dt
import uuid

from sqlalchemy import DateTime, Uuid, func, text
from sqlalchemy.orm import Mapped, mapped_column


class UUIDPrimaryKey:
    """UUID PK generated by Postgres.

    UUIDs rather than sequential integers: party invite codes and leaderboards
    expose IDs to other users, and sequential IDs would leak total user counts
    and allow trivial enumeration. gen_random_uuid() is built into Postgres 13+
    (we run 17), so no pgcrypto extension is required.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class Timestamps:
    """created_at / updated_at, both timezone-aware.

    TIMESTAMPTZ throughout: this app is entirely about when things happened,
    and daily resets are timezone-sensitive.
    """

    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
