"""gym workout module

Revision ID: 085f917f46f8
Revises: fa8ce42996db
Create Date: 2026-09-10 09:01:40.998878
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '085f917f46f8'
down_revision: str | None = 'fa8ce42996db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_measurements',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=True),
    sa.Column('value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("(metric = 'custom') = (label IS NOT NULL)", name='ck_body_measurements_label'),
    sa.CheckConstraint("(metric = 'weight' AND unit IN ('kg', 'lb')) OR (metric = 'body_fat' AND unit = 'percent') OR metric = 'custom'", name='ck_body_measurements_unit_for_metric'),
    sa.CheckConstraint("metric IN ('weight', 'body_fat', 'custom')", name='ck_body_measurements_metric'),
    sa.CheckConstraint("unit IN ('kg', 'lb', 'percent', 'cm', 'in')", name='ck_body_measurements_unit'),
    sa.CheckConstraint('value > 0 AND value < 100000', name='ck_body_measurements_value'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_body_measurements_user_metric_time', 'body_measurements', ['user_id', 'metric', 'recorded_at'], unique=False)
    op.create_table('exercises',
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_key', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('primary_muscle_groups', postgresql.ARRAY(sa.String(length=32)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('equipment', sa.String(length=32), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('is_custom', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('strength', 'cardio', 'bodyweight', 'mobility')", name='ck_exercises_category'),
    sa.CheckConstraint("equipment IN ('barbell', 'dumbbell', 'machine', 'cable', 'kettlebell', 'bodyweight', 'band', 'smith_machine', 'ez_bar', 'trap_bar', 'plate', 'cardio_machine', 'other')", name='ck_exercises_equipment'),
    sa.CheckConstraint("primary_muscle_groups <@ ARRAY['chest', 'back', 'lats', 'traps', 'shoulders', 'biceps', 'triceps', 'forearms', 'abs', 'obliques', 'lower_back', 'glutes', 'quads', 'hamstrings', 'calves', 'adductors', 'abductors', 'neck', 'full_body', 'cardio']::varchar[] AND cardinality(primary_muscle_groups) >= 1", name='ck_exercises_muscle_groups'),
    sa.CheckConstraint('(is_custom AND created_by_user_id IS NOT NULL AND slug IS NULL) OR (NOT is_custom AND created_by_user_id IS NULL AND slug IS NOT NULL)', name='ck_exercises_owner'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_created_by_user_id'), 'exercises', ['created_by_user_id'], unique=False)
    op.create_index('ix_exercises_muscle_groups', 'exercises', ['primary_muscle_groups'], unique=False, postgresql_using='gin')
    op.create_index('uq_exercises_custom_name', 'exercises', ['created_by_user_id', 'name_key'], unique=True, postgresql_where=sa.text('is_custom'))
    op.create_index('uq_exercises_library_name', 'exercises', ['name_key'], unique=True, postgresql_where=sa.text('NOT is_custom'))
    op.create_index('uq_exercises_library_slug', 'exercises', ['slug'], unique=True, postgresql_where=sa.text('NOT is_custom'))
    op.create_table('routines',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(name) >= 1', name='ck_routines_name'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routines_user_id'), 'routines', ['user_id'], unique=False)
    op.create_table('routine_exercises',
    sa.Column('routine_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=True),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('target_weight_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_routine_exercises_position'),
    sa.CheckConstraint('rest_seconds IS NULL OR (rest_seconds >= 0 AND rest_seconds <= 3600)', name='ck_routine_exercises_rest'),
    sa.CheckConstraint('target_reps IS NULL OR (target_reps >= 1 AND target_reps <= 1000)', name='ck_routine_exercises_target_reps'),
    sa.CheckConstraint('target_sets IS NULL OR (target_sets >= 1 AND target_sets <= 50)', name='ck_routine_exercises_target_sets'),
    sa.CheckConstraint('target_weight_kg IS NULL OR (target_weight_kg >= 0 AND target_weight_kg <= 1000)', name='ck_routine_exercises_target_weight'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_id', 'position', name='uq_routine_exercise_position')
    )
    op.create_index(op.f('ix_routine_exercises_exercise_id'), 'routine_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_routine_exercises_routine_id'), 'routine_exercises', ['routine_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('routine_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='in_progress', nullable=False),
    sa.Column('qualified', sa.Boolean(), nullable=True),
    sa.Column('week_key', sa.String(length=16), nullable=True),
    sa.Column('points_credited', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'in_progress') = (ended_at IS NULL)", name='ck_workout_sessions_ended'),
    sa.CheckConstraint("status IN ('in_progress', 'completed', 'abandoned')", name='ck_workout_sessions_status'),
    sa.CheckConstraint('points_credited >= 0', name='ck_workout_sessions_points_non_negative'),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_sessions_user_started', 'workout_sessions', ['user_id', 'started_at'], unique=False)
    op.create_index('ix_workout_sessions_user_week', 'workout_sessions', ['user_id', 'week_key'], unique=False)
    op.create_index('uq_workout_sessions_one_active', 'workout_sessions', ['user_id'], unique=True, postgresql_where=sa.text("status = 'in_progress'"))
    op.create_table('points_ledger',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('period_key', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("(source_type = 'reversal' AND points < 0) OR (source_type <> 'reversal' AND points > 0)", name='ck_points_ledger_sign'),
    sa.CheckConstraint("(source_type = 'streak_bonus') = (period_key IS NOT NULL)", name='ck_points_ledger_period_key'),
    sa.CheckConstraint("source_type IN ('set_logged', 'session_completed', 'pr_achieved', 'streak_bonus', 'reversal')", name='ck_points_ledger_source'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_ledger_session_id'), 'points_ledger', ['session_id'], unique=False)
    op.create_index('ix_points_ledger_user_time', 'points_ledger', ['user_id', 'created_at'], unique=False)
    op.create_index('uq_points_ledger_once', 'points_ledger', ['source_type', 'source_id'], unique=True, postgresql_where=sa.text("source_type IN ('session_completed', 'streak_bonus', 'reversal')"))
    op.create_index('uq_points_ledger_streak_week', 'points_ledger', ['user_id', 'period_key'], unique=True, postgresql_where=sa.text("source_type = 'streak_bonus'"))
    op.create_table('set_entries',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=7, scale=2), server_default='0', nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_pr', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_set_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('distance_m IS NULL OR (distance_m > 0 AND distance_m <= 1000000)', name='ck_set_entries_distance'),
    sa.CheckConstraint('duration_seconds IS NULL OR (duration_seconds >= 1 AND duration_seconds <= 86400)', name='ck_set_entries_duration'),
    sa.CheckConstraint('reps IS NOT NULL OR duration_seconds IS NOT NULL OR distance_m IS NOT NULL', name='ck_set_entries_has_measure'),
    sa.CheckConstraint('reps IS NULL OR (reps >= 1 AND reps <= 1000)', name='ck_set_entries_reps'),
    sa.CheckConstraint('rpe IS NULL OR (rpe >= 1 AND rpe <= 10)', name='ck_set_entries_rpe'),
    sa.CheckConstraint('set_number >= 1', name='ck_set_entries_set_number'),
    sa.CheckConstraint('weight_kg >= 0 AND weight_kg <= 1000', name='ck_set_entries_weight'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'client_set_id', name='uq_set_entries_client_id')
    )
    op.create_index(op.f('ix_set_entries_exercise_id'), 'set_entries', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_set_entries_session_id'), 'set_entries', ['session_id'], unique=False)
    op.create_index('ix_set_entries_user_exercise_time', 'set_entries', ['user_id', 'exercise_id', 'completed_at'], unique=False)
    op.create_table('personal_records',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('record_type', sa.String(length=24), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('previous_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('set_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("(record_type = 'max_volume') = (set_id IS NULL)", name='ck_personal_records_set_scope'),
    sa.CheckConstraint("record_type IN ('max_weight', 'max_reps_at_weight', 'est_1rm', 'max_volume')", name='ck_personal_records_type'),
    sa.CheckConstraint('value > 0', name='ck_personal_records_value_positive'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['set_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_id', 'record_type', name='uq_personal_records_set_type')
    )
    op.create_index(op.f('ix_personal_records_session_id'), 'personal_records', ['session_id'], unique=False)
    op.create_index('ix_personal_records_user_exercise_type', 'personal_records', ['user_id', 'exercise_id', 'record_type'], unique=False)
    op.create_index('uq_personal_records_session_volume', 'personal_records', ['session_id', 'exercise_id'], unique=True, postgresql_where=sa.text("record_type = 'max_volume'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_personal_records_session_volume', table_name='personal_records', postgresql_where=sa.text("record_type = 'max_volume'"))
    op.drop_index('ix_personal_records_user_exercise_type', table_name='personal_records')
    op.drop_index(op.f('ix_personal_records_session_id'), table_name='personal_records')
    op.drop_table('personal_records')
    op.drop_index('ix_set_entries_user_exercise_time', table_name='set_entries')
    op.drop_index(op.f('ix_set_entries_session_id'), table_name='set_entries')
    op.drop_index(op.f('ix_set_entries_exercise_id'), table_name='set_entries')
    op.drop_table('set_entries')
    op.drop_index('uq_points_ledger_streak_week', table_name='points_ledger', postgresql_where=sa.text("source_type = 'streak_bonus'"))
    op.drop_index('uq_points_ledger_once', table_name='points_ledger', postgresql_where=sa.text("source_type IN ('session_completed', 'streak_bonus', 'reversal')"))
    op.drop_index('ix_points_ledger_user_time', table_name='points_ledger')
    op.drop_index(op.f('ix_points_ledger_session_id'), table_name='points_ledger')
    op.drop_table('points_ledger')
    op.drop_index('uq_workout_sessions_one_active', table_name='workout_sessions', postgresql_where=sa.text("status = 'in_progress'"))
    op.drop_index('ix_workout_sessions_user_week', table_name='workout_sessions')
    op.drop_index('ix_workout_sessions_user_started', table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_routine_exercises_routine_id'), table_name='routine_exercises')
    op.drop_index(op.f('ix_routine_exercises_exercise_id'), table_name='routine_exercises')
    op.drop_table('routine_exercises')
    op.drop_index(op.f('ix_routines_user_id'), table_name='routines')
    op.drop_table('routines')
    op.drop_index('uq_exercises_library_slug', table_name='exercises', postgresql_where=sa.text('NOT is_custom'))
    op.drop_index('uq_exercises_library_name', table_name='exercises', postgresql_where=sa.text('NOT is_custom'))
    op.drop_index('uq_exercises_custom_name', table_name='exercises', postgresql_where=sa.text('is_custom'))
    op.drop_index('ix_exercises_muscle_groups', table_name='exercises', postgresql_using='gin')
    op.drop_index(op.f('ix_exercises_created_by_user_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index('ix_body_measurements_user_metric_time', table_name='body_measurements')
    op.drop_table('body_measurements')
    # ### end Alembic commands ###
