"""party raids

Revision ID: 1c724fa16b8e
Revises: ce1968933857
Create Date: 2026-09-14 15:13:00.280894
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1c724fa16b8e'
down_revision: str | None = 'ce1968933857'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raid_bosses',
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('week_key', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('defeated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('damage >= 0', name='ck_raid_bosses_damage'),
    sa.CheckConstraint('max_hp > 0', name='ck_raid_bosses_max_hp'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id', 'week_key', name='uq_raid_bosses_party_week')
    )
    op.create_index(op.f('ix_raid_bosses_party_id'), 'raid_bosses', ['party_id'], unique=False)
    op.create_table('raid_hits',
    sa.Column('boss_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('damage > 0', name='ck_raid_hits_damage'),
    sa.ForeignKeyConstraint(['boss_id'], ['raid_bosses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('boss_id', 'session_id', name='uq_raid_hits_boss_session')
    )
    op.create_index(op.f('ix_raid_hits_boss_id'), 'raid_hits', ['boss_id'], unique=False)
    op.create_index(op.f('ix_raid_hits_user_id'), 'raid_hits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raid_hits_user_id'), table_name='raid_hits')
    op.drop_index(op.f('ix_raid_hits_boss_id'), table_name='raid_hits')
    op.drop_table('raid_hits')
    op.drop_index(op.f('ix_raid_bosses_party_id'), table_name='raid_bosses')
    op.drop_table('raid_bosses')
    # ### end Alembic commands ###
