"""user weight unit

Revision ID: 2caadc5c9d12
Revises: 085f917f46f8
Create Date: 2026-09-10 16:55:01.396200
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2caadc5c9d12'
down_revision: str | None = '085f917f46f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('weight_unit', sa.String(length=2), server_default='kg', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight_unit')
    # ### end Alembic commands ###
