"""character class

Revision ID: 4e45653249de
Revises: 6fcf270d2e3d
Create Date: 2026-09-16 21:20:42.804668
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4e45653249de'
down_revision: str | None = '6fcf270d2e3d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('character_class', sa.String(length=16), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'character_class')
    # ### end Alembic commands ###
