"""rank trials

Revision ID: 5a043429ab94
Revises: 1c724fa16b8e
Create Date: 2026-09-14 15:30:50.721053
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5a043429ab94'
down_revision: str | None = '1c724fa16b8e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level_progress', sa.Column('trials_passed', sa.String(length=3), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('level_progress', 'trials_passed')
    # ### end Alembic commands ###
