"""initial schema: users, quests, completions, rewards, parties

Revision ID: 5dba70011569
Revises: 
Create Date: 2026-09-10 03:19:18.349252
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5dba70011569'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(display_name) >= 1', name='ck_users_display_name'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email_normalized'), 'users', ['email_normalized'], unique=True)
    op.create_table('level_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('total_xp', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('current_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('rank', sa.Enum('E', 'D', 'C', 'B', 'A', 'S', name='rank'), server_default='E', nullable=False),
    sa.Column('points_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_completed_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_level >= 1', name='ck_progress_level_min'),
    sa.CheckConstraint('points_balance >= 0', name='ck_progress_points_non_negative'),
    sa.CheckConstraint('total_xp >= 0', name='ck_progress_xp_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('parties',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('invite_code', sa.String(length=10), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('max_members', sa.Integer(), server_default='8', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_members >= 1 AND max_members <= 100', name='ck_parties_max_members'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_invite_code'), 'parties', ['invite_code'], unique=True)
    op.create_index(op.f('ix_parties_owner_id'), 'parties', ['owner_id'], unique=False)
    op.create_table('quests',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('points_reward', sa.Integer(), server_default='0', nullable=False),
    sa.Column('recurrence', sa.String(length=16), server_default='none', nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='quest_status'), server_default='active', nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("recurrence IN ('none', 'daily', 'weekly')", name='ck_quests_recurrence'),
    sa.CheckConstraint('points_reward >= 0', name='ck_quests_points_non_negative'),
    sa.CheckConstraint('xp_reward >= 0 AND xp_reward <= 10000', name='ck_quests_xp_reward_range'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quests_owner_id'), 'quests', ['owner_id'], unique=False)
    op.create_index('ix_quests_owner_status', 'quests', ['owner_id', 'status'], unique=False)
    op.create_table('reward_items',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('point_cost', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('point_cost > 0', name='ck_reward_items_cost_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reward_items_owner_active', 'reward_items', ['owner_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_reward_items_owner_id'), 'reward_items', ['owner_id'], unique=False)
    op.create_table('party_memberships',
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='party_role'), server_default='member', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('party_id', 'user_id')
    )
    op.create_index('ix_party_memberships_user', 'party_memberships', ['user_id'], unique=False)
    op.create_table('party_quests',
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('points_reward', sa.Integer(), server_default='0', nullable=False),
    sa.Column('recurrence', sa.String(length=16), server_default='none', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("recurrence IN ('none', 'daily', 'weekly')", name='ck_party_quests_recurrence'),
    sa.CheckConstraint('points_reward >= 0', name='ck_party_quests_points_non_negative'),
    sa.CheckConstraint('xp_reward >= 0 AND xp_reward <= 10000', name='ck_party_quests_xp_reward_range'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_party_quests_party_id'), 'party_quests', ['party_id'], unique=False)
    op.create_table('quest_completions',
    sa.Column('quest_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('period_key', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('points_awarded >= 0', name='ck_completion_points_non_negative'),
    sa.CheckConstraint('xp_awarded >= 0', name='ck_completion_xp_non_negative'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quest_id', 'user_id', 'period_key', name='uq_quest_completion_period')
    )
    op.create_index(op.f('ix_quest_completions_quest_id'), 'quest_completions', ['quest_id'], unique=False)
    op.create_index(op.f('ix_quest_completions_user_id'), 'quest_completions', ['user_id'], unique=False)
    op.create_index('ix_quest_completions_user_time', 'quest_completions', ['user_id', 'completed_at'], unique=False)
    op.create_table('reward_redemptions',
    sa.Column('reward_item_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('points_spent', sa.Integer(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('points_spent >= 0', name='ck_redemption_points_non_negative'),
    sa.ForeignKeyConstraint(['reward_item_id'], ['reward_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_redemptions_reward_item_id'), 'reward_redemptions', ['reward_item_id'], unique=False)
    op.create_index(op.f('ix_reward_redemptions_user_id'), 'reward_redemptions', ['user_id'], unique=False)
    op.create_table('party_quest_completions',
    sa.Column('party_quest_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('period_key', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('points_awarded >= 0', name='ck_pq_completion_points_non_negative'),
    sa.CheckConstraint('xp_awarded >= 0', name='ck_pq_completion_xp_non_negative'),
    sa.ForeignKeyConstraint(['party_quest_id'], ['party_quests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_quest_id', 'user_id', 'period_key', name='uq_party_quest_completion_period')
    )
    op.create_index(op.f('ix_party_quest_completions_party_quest_id'), 'party_quest_completions', ['party_quest_id'], unique=False)
    op.create_index(op.f('ix_party_quest_completions_user_id'), 'party_quest_completions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_party_quest_completions_user_id'), table_name='party_quest_completions')
    op.drop_index(op.f('ix_party_quest_completions_party_quest_id'), table_name='party_quest_completions')
    op.drop_table('party_quest_completions')
    op.drop_index(op.f('ix_reward_redemptions_user_id'), table_name='reward_redemptions')
    op.drop_index(op.f('ix_reward_redemptions_reward_item_id'), table_name='reward_redemptions')
    op.drop_table('reward_redemptions')
    op.drop_index('ix_quest_completions_user_time', table_name='quest_completions')
    op.drop_index(op.f('ix_quest_completions_user_id'), table_name='quest_completions')
    op.drop_index(op.f('ix_quest_completions_quest_id'), table_name='quest_completions')
    op.drop_table('quest_completions')
    op.drop_index(op.f('ix_party_quests_party_id'), table_name='party_quests')
    op.drop_table('party_quests')
    op.drop_index('ix_party_memberships_user', table_name='party_memberships')
    op.drop_table('party_memberships')
    op.drop_index(op.f('ix_reward_items_owner_id'), table_name='reward_items')
    op.drop_index('ix_reward_items_owner_active', table_name='reward_items')
    op.drop_table('reward_items')
    op.drop_index('ix_quests_owner_status', table_name='quests')
    op.drop_index(op.f('ix_quests_owner_id'), table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_parties_owner_id'), table_name='parties')
    op.drop_index(op.f('ix_parties_invite_code'), table_name='parties')
    op.drop_table('parties')
    op.drop_table('level_progress')
    op.drop_index(op.f('ix_users_email_normalized'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # HAND-ADDED - autogenerate does not emit these.
    # SQLAlchemy creates a native Postgres enum type implicitly with the first
    # table that uses it, but drop_table does NOT drop the type. Without this,
    # a downgrade leaves 'rank'/'quest_status'/'party_role' behind and the next
    # upgrade fails with: type "rank" already exists.
    # Verified by running upgrade -> downgrade -> upgrade against Postgres 17.
    for enum_name in ("rank", "quest_status", "party_role"):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
