"""weekly leagues

Revision ID: 676864270370
Revises: 4e45653249de
Create Date: 2026-09-16 21:36:32.378624
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '676864270370'
down_revision: str | None = '4e45653249de'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('week_key', sa.String(length=16), nullable=False),
    sa.Column('division', sa.Integer(), server_default='0', nullable=False),
    sa.Column('group_no', sa.Integer(), server_default='0', nullable=False),
    sa.Column('promoted_from', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('division >= 0', name='ck_league_memberships_division'),
    sa.CheckConstraint('group_no >= 0', name='ck_league_memberships_group'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_key', name='uq_league_memberships_user_week')
    )
    op.create_index('ix_league_memberships_group', 'league_memberships', ['week_key', 'division', 'group_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_league_memberships_group', table_name='league_memberships')
    op.drop_table('league_memberships')
    # ### end Alembic commands ###
