"""workout imports

Revision ID: 6fcf270d2e3d
Revises: 5a043429ab94
Create Date: 2026-09-14 16:42:35.496474
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6fcf270d2e3d'
down_revision: str | None = '5a043429ab94'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_imports',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('workouts', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('exercises_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('xp_awarded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('strong', 'hevy')", name='ck_workout_imports_source'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'file_hash', name='uq_workout_imports_user_file')
    )
    op.add_column('workout_sessions', sa.Column('import_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_workout_sessions_import_id'), 'workout_sessions', ['import_id'], unique=False)
    op.create_foreign_key('fk_workout_sessions_import_id_workout_imports', 'workout_sessions', 'workout_imports', ['import_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_workout_sessions_import_id_workout_imports', 'workout_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_workout_sessions_import_id'), table_name='workout_sessions')
    op.drop_column('workout_sessions', 'import_id')
    op.drop_table('workout_imports')
    # ### end Alembic commands ###
