"""push devices

Adds push_devices: one row per APNs device token, tied to the user AND the
sign-in session that registered it, so signing out of a phone stops its
notifications. The token is UNIQUE across users - it identifies the app
install, not the person - so a second account signing in on the same phone
takes the row over instead of both being notified. New table only; nothing
existing changes.

Revision ID: e6ab950c84ea
Revises: 676864270370
Create Date: 2026-09-19 17:59:07.016900
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e6ab950c84ea'
down_revision: str | None = '676864270370'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_devices',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('environment', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("environment IN ('sandbox', 'production')", name='ck_push_devices_environment'),
    sa.ForeignKeyConstraint(['session_id'], ['auth_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_push_devices_session_id'), 'push_devices', ['session_id'], unique=False)
    op.create_index(op.f('ix_push_devices_user_id'), 'push_devices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_devices_user_id'), table_name='push_devices')
    op.drop_index(op.f('ix_push_devices_session_id'), table_name='push_devices')
    op.drop_table('push_devices')
    # ### end Alembic commands ###
