"""party max_members default 8 to 10

Revision ID: fa8ce42996db
Revises: 5dba70011569
Create Date: 2026-09-10 07:01:51.148363
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fa8ce42996db'
down_revision: str | None = '5dba70011569'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Raise the default party size cap from 8 to 10.

    Only the DEFAULT changes: existing parties keep whatever max_members they
    were created with, which is the intended behaviour - a live party should
    not silently change size because the default moved.
    """
    op.alter_column('parties', 'max_members',
               existing_type=sa.INTEGER(),
               server_default='10',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parties', 'max_members',
               existing_type=sa.INTEGER(),
               server_default=sa.text('8'),
               existing_nullable=False)
    # ### end Alembic commands ###
